nombre = "alejo",
apellidos = "jimenez",
edad = 21,
email = "alejosamp@gmail.com",
telefono = 3146782919,
casado = False,
conHijos = False,
listaDeAmigos = ["juan", "pedro", "jesus"],
paliculasVistas = {1: "harry potter", 2: "terminator", 3: "ligthyear"},

print(nombre),
print(apellidos),
print(edad),
print(email),
print(telefono),
print(casado),
print(conHijos),
print(listaDeAmigos),
print(paliculasVistas),
